### ISSUE TITLE
[BasicLayout] logo可以调样式

### ISSUE THREAD

**Issue by xingyuefeng** [uiwjs/uiw-admin#148]
当前传入logo属性 不能修改样式

**Comment by wj0990** [comment]
收到

**Comment by wangwei88** [comment]
basic-layouts  头像可以支持取姓名的第一个字

**Comment by wj0990** [comment]
可以在BasicLayout 引入css 样式

```css
  .uiw-admin-global-header .uiw-admin-global-title-top img {
     border-radius: 50%;
     background-color: red;
     margin-right:12px;
}
```
`BasicLayout` 新增`style`属性 `className` 方便自定义子节点样式。
